version: '3.7'
services:
  rdb:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    container_name: starter-rdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starter
      MYSQL_USER: starter
      MYSQL_PASSWORD: starter
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
