version: '3.7'
services:
  rdb:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    container_name: community-rdb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: community
      MYSQL_DATABASE: community
      MYSQL_USER: community
      MYSQL_PASSWORD: community
    ports:
      - 3307:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql
