spring:
  application:
    name: starter-api
  messages:
    encoding: UTF-8
  profiles:
    include:
      - core

server:
  port: 9901
  error:
    whitelabel:
      enabled: false
  shutdown: graceful
  tomcat:
    accesslog:
      enabled: true
      directory:
      prefix: api-access-log
    basedir: logs/tomcat/api/