logging:
  level:
    root: INFO
    com.starter: DEBUG
    org:hibernate:
      SQL: debug
      type.descriptor.sql: trace


spring:
  config:
    activate:
      on-profile: local


---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starter
    username: starter
    password: starter
    configuration:
      hikari:
        auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        default_batch_fetch_size: 1000


starter:
  security:
    swagger-ui-path: /document/swagger-ui/index.html

springdoc:
  packagesToScan: com.starter.api.app
  api-docs:
    enabled: true
    path: /document/api-docs
  swagger-ui:
    enabled: true
    path: /document/swagger-ui.html


sleuth:
  sampler:
    probability: 1.0
