logging:
  level:
    root: INFO
    org:
      springframework:
        boot:
          autoconfigure: ERROR

spring:
  config:
    activate:
      on-profile: release

starter:
  security:
    swagger-ui-path: /document/swagger-ui/index.html


springdoc:
  packagesToScan: com.starter.api.app
  api-docs:
    enabled: false
    path: /document/api-docs
  swagger-ui:
    enabled: false
    path: /document/swagger-ui.html

sleuth:
  sampler:
    probability: 1.0
